version: '3.9'

services:
  api:
    build: .
    container_name: autofi_express_app
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    command: npm run dev

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
